package com.Shop.entity;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.
/**
 * Entity mapped to table "SHOP".
 */
@Entity
public class Shop {

    @Id
    private Long id;
    private String clickid;
    private Boolean isclick;

    @Generated(hash = 633476670)
    public Shop() {
    }

    public Shop(Long id) {
        this.id = id;
    }

    @Generated(hash = 2412844)
    public Shop(Long id, String clickid, Boolean isclick) {
        this.id = id;
        this.clickid = clickid;
        this.isclick = isclick;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getClickid() {
        return clickid;
    }

    public void setClickid(String clickid) {
        this.clickid = clickid;
    }

    public Boolean getIsclick() {
        return isclick;
    }

    public void setIsclick(Boolean isclick) {
        this.isclick = isclick;
    }

}
