package com.zxly.o2o.model;

public class UserInfoVO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.id
     *
     * @mbggenerated Sun Jan 04 17:02:23 CST 2015
     */
    private long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.user_name
     *
     * @mbggenerated Sun Jan 04 17:02:23 CST 2015
     */
    private String userName="";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.password
     *
     * @mbggenerated Sun Jan 04 17:02:23 CST 2015
     */
    private String password="";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.nickname
     *
     * @mbggenerated Sun Jan 04 17:02:23 CST 2015
     */
    private String nickname="";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.type
     *
     * @mbggenerated Sun Jan 04 17:02:23 CST 2015
     */
    private Byte type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.origin_type
     *
     * @mbggenerated Sun Jan 04 17:02:23 CST 2015
     */
    private Byte originType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.shop_id
     *
     * @mbggenerated Sun Jan 04 17:02:23 CST 2015
     */
    private long shopId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.regist_shop_id
     *
     * @mbggenerated Sun Jan 04 17:02:23 CST 2015
     */
    private long registShopId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.name
     *
     * @mbggenerated Sun Jan 04 17:02:23 CST 2015
     */
    private String name="";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.gender
     *
     * @mbggenerated Sun Jan 04 17:02:23 CST 2015
     */
    private Byte gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.description
     *
     * @mbggenerated Sun Jan 04 17:02:23 CST 2015
     */
    private String description="";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.mobile_phone
     *
     * @mbggenerated Sun Jan 04 17:02:23 CST 2015
     */
    private String mobilePhone="";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.birthday
     *
     * @mbggenerated Sun Jan 04 17:02:23 CST 2015
     */
    private long birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.login_time
     *
     * @mbggenerated Sun Jan 04 17:02:23 CST 2015
     */
    private long loginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.origin_head_url
     *
     * @mbggenerated Sun Jan 04 17:02:23 CST 2015
     */
    private String originHeadUrl="";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.thum_head_url
     *
     * @mbggenerated Sun Jan 04 17:02:23 CST 2015
     */
    private String thumHeadUrl="";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.ip
     *
     * @mbggenerated Sun Jan 04 17:02:23 CST 2015
     */
    private String ip="";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.status
     *
     * @mbggenerated Sun Jan 04 17:02:23 CST 2015
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.pass_time
     *
     * @mbggenerated Sun Jan 04 17:02:23 CST 2015
     */
    private long passTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.create_time
     *
     * @mbggenerated Sun Jan 04 17:02:23 CST 2015
     */
    private long createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.update_time
     *
     * @mbggenerated Sun Jan 04 17:02:23 CST 2015
     */
    private long updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.id
     *
     * @return the value of user_info.id
     *
     * @mbggenerated Sun Jan 04 17:02:23 CST 2015
     */
    public long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.id
     *
     * @param id the value for user_info.id
     *
     * @mbggenerated Sun Jan 04 17:02:23 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.user_name
     *
     * @return the value of user_info.user_name
     *
     * @mbggenerated Sun Jan 04 17:02:23 CST 2015
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.user_name
     *
     * @param userName the value for user_info.user_name
     *
     * @mbggenerated Sun Jan 04 17:02:23 CST 2015
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.password
     *
     * @return the value of user_info.password
     *
     * @mbggenerated Sun Jan 04 17:02:23 CST 2015
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.password
     *
     * @param password the value for user_info.password
     *
     * @mbggenerated Sun Jan 04 17:02:23 CST 2015
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.nickname
     *
     * @return the value of user_info.nickname
     *
     * @mbggenerated Sun Jan 04 17:02:23 CST 2015
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.nickname
     *
     * @param nickname the value for user_info.nickname
     *
     * @mbggenerated Sun Jan 04 17:02:23 CST 2015
     */
    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.type
     *
     * @return the value of user_info.type
     *
     * @mbggenerated Sun Jan 04 17:02:23 CST 2015
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.type
     *
     * @param type the value for user_info.type
     *
     * @mbggenerated Sun Jan 04 17:02:23 CST 2015
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.origin_type
     *
     * @return the value of user_info.origin_type
     *
     * @mbggenerated Sun Jan 04 17:02:23 CST 2015
     */
    public Byte getOriginType() {
        return originType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.origin_type
     *
     * @param originType the value for user_info.origin_type
     *
     * @mbggenerated Sun Jan 04 17:02:23 CST 2015
     */
    public void setOriginType(Byte originType) {
        this.originType = originType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.shop_id
     *
     * @return the value of user_info.shop_id
     *
     * @mbggenerated Sun Jan 04 17:02:23 CST 2015
     */
    public Long getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.shop_id
     *
     * @param shopId the value for user_info.shop_id
     *
     * @mbggenerated Sun Jan 04 17:02:23 CST 2015
     */
    public void setShopId(Long shopId) {
        this.shopId = shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.regist_shop_id
     *
     * @return the value of user_info.regist_shop_id
     *
     * @mbggenerated Sun Jan 04 17:02:23 CST 2015
     */
    public Long getRegistShopId() {
        return registShopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.regist_shop_id
     *
     * @param registShopId the value for user_info.regist_shop_id
     *
     * @mbggenerated Sun Jan 04 17:02:23 CST 2015
     */
    public void setRegistShopId(Long registShopId) {
        this.registShopId = registShopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.name
     *
     * @return the value of user_info.name
     *
     * @mbggenerated Sun Jan 04 17:02:23 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.name
     *
     * @param name the value for user_info.name
     *
     * @mbggenerated Sun Jan 04 17:02:23 CST 2015
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.gender
     *
     * @return the value of user_info.gender
     *
     * @mbggenerated Sun Jan 04 17:02:23 CST 2015
     */
    public Byte getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.gender
     *
     * @param gender the value for user_info.gender
     *
     * @mbggenerated Sun Jan 04 17:02:23 CST 2015
     */
    public void setGender(Byte gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.description
     *
     * @return the value of user_info.description
     *
     * @mbggenerated Sun Jan 04 17:02:23 CST 2015
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.description
     *
     * @param description the value for user_info.description
     *
     * @mbggenerated Sun Jan 04 17:02:23 CST 2015
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.mobile_phone
     *
     * @return the value of user_info.mobile_phone
     *
     * @mbggenerated Sun Jan 04 17:02:23 CST 2015
     */
    public String getMobilePhone() {
        return mobilePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.mobile_phone
     *
     * @param mobilePhone the value for user_info.mobile_phone
     *
     * @mbggenerated Sun Jan 04 17:02:23 CST 2015
     */
    public void setMobilePhone(String mobilePhone) {
        this.mobilePhone = mobilePhone == null ? null : mobilePhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.birthday
     *
     * @return the value of user_info.birthday
     *
     * @mbggenerated Sun Jan 04 17:02:23 CST 2015
     */
    public Long getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.birthday
     *
     * @param birthday the value for user_info.birthday
     *
     * @mbggenerated Sun Jan 04 17:02:23 CST 2015
     */
    public void setBirthday(Long birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.login_time
     *
     * @return the value of user_info.login_time
     *
     * @mbggenerated Sun Jan 04 17:02:23 CST 2015
     */
    public Long getLoginTime() {
        return loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.login_time
     *
     * @param loginTime the value for user_info.login_time
     *
     * @mbggenerated Sun Jan 04 17:02:23 CST 2015
     */
    public void setLoginTime(Long loginTime) {
        this.loginTime = loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.origin_head_url
     *
     * @return the value of user_info.origin_head_url
     *
     * @mbggenerated Sun Jan 04 17:02:23 CST 2015
     */
    public String getOriginHeadUrl() {
        return originHeadUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.origin_head_url
     *
     * @param originHeadUrl the value for user_info.origin_head_url
     *
     * @mbggenerated Sun Jan 04 17:02:23 CST 2015
     */
    public void setOriginHeadUrl(String originHeadUrl) {
        this.originHeadUrl = originHeadUrl == null ? null : originHeadUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.thum_head_url
     *
     * @return the value of user_info.thum_head_url
     *
     * @mbggenerated Sun Jan 04 17:02:23 CST 2015
     */
    public String getThumHeadUrl() {
        return thumHeadUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.thum_head_url
     *
     * @param thumHeadUrl the value for user_info.thum_head_url
     *
     * @mbggenerated Sun Jan 04 17:02:23 CST 2015
     */
    public void setThumHeadUrl(String thumHeadUrl) {
        this.thumHeadUrl = thumHeadUrl == null ? null : thumHeadUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.ip
     *
     * @return the value of user_info.ip
     *
     * @mbggenerated Sun Jan 04 17:02:23 CST 2015
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.ip
     *
     * @param ip the value for user_info.ip
     *
     * @mbggenerated Sun Jan 04 17:02:23 CST 2015
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.status
     *
     * @return the value of user_info.status
     *
     * @mbggenerated Sun Jan 04 17:02:23 CST 2015
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.status
     *
     * @param status the value for user_info.status
     *
     * @mbggenerated Sun Jan 04 17:02:23 CST 2015
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.pass_time
     *
     * @return the value of user_info.pass_time
     *
     * @mbggenerated Sun Jan 04 17:02:23 CST 2015
     */
    public Long getPassTime() {
        return passTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.pass_time
     *
     * @param passTime the value for user_info.pass_time
     *
     * @mbggenerated Sun Jan 04 17:02:23 CST 2015
     */
    public void setPassTime(Long passTime) {
        this.passTime = passTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.create_time
     *
     * @return the value of user_info.create_time
     *
     * @mbggenerated Sun Jan 04 17:02:23 CST 2015
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.create_time
     *
     * @param createTime the value for user_info.create_time
     *
     * @mbggenerated Sun Jan 04 17:02:23 CST 2015
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.update_time
     *
     * @return the value of user_info.update_time
     *
     * @mbggenerated Sun Jan 04 17:02:23 CST 2015
     */
    public Long getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.update_time
     *
     * @param updateTime the value for user_info.update_time
     *
     * @mbggenerated Sun Jan 04 17:02:23 CST 2015
     */
    public void setUpdateTime(Long updateTime) {
        this.updateTime = updateTime;
    }
}